In [ ]:
"""
1.	Create a 2D NumPy array with dimensions 5x5, filled with integers from 1 to 25.
    Use slicing to:
        Extract and display the third row of the array.
	    Extract and display the second column of the array.

"""

In [4]:
import numpy as np

array1 = np.arange(1, 26).reshape(5, 5)     #2D NumPy array with dimensions 5x5, filled with integers from 1 to 25
print("matrix[5,5] : ")
print(array1)
print()


row = array1[2, :]                          # Display the third row 
print(f"third row     :{row}")
print()

col = array1[:, 1]                           #  Display the second column
print(f"second column :{col}")

matrix[5,5] : 
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

third row     :[11 12 13 14 15]

second column :[ 2  7 12 17 22]


In [ ]:
"""
2.	Create a 2D NumPy array with dimensions 3x4, filled with any integers of your choice. 
    Access and print the element at the second row and third column.

"""

In [13]:

array1 = np.random.randint(low=0, high=100, size=(3, 4))          #  NumPy array [3x4], filled with random numbers
print("matrix[3,4] : ")
print(array1)
print()

num = array1[1, 2]                                                #  Second row and third column
print(f"The number in the second row and third column: {num}")

matrix[3,4] : 
[[78 88 63 58]
 [73 48 30 50]
 [66 37 96 80]]

The number in the second row and third column: 30


In [ ]:
""" 
3.	Create two NumPyarrays of the same size with random integers. 
    Calculate their element-wise sum and then display elements from new arrays wherever the sum is greater than 50.
"""

In [14]:
array1 = np.random.randint(low=10, high=35, size=(3, 3))
array2 = np.random.randint(low=10, high=35, size=(3, 3))


print("Array 1:")
print(array1)
print()

print("Array 2:")
print(array2)
print()


array_sum = np.add(array1, array2)   # The sum of their elements

# display the sum array
print("Sum of arrays:")              # display the sum 
print(array_sum)

print("Elements where sum is greater than 50:")
print(f"From  array 1   :{array1[array_sum > 50]}")
print(f"From  array 2   :{array2[array_sum > 50]}")
print(f"Where sum array :{array_sum[array_sum > 50]}")

Array 1:
[[24 22 21]
 [25 11 19]
 [16 29 33]]

Array 2:
[[18 32 14]
 [12 16 11]
 [12 17 11]]

Sum of arrays:
[[42 54 35]
 [37 27 30]
 [28 46 44]]
Elements where sum is greater than 50:
From  array 1   :[22]
From  array 2   :[32]
Where sum array :[54]
